# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swift}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shane Hanna", "Bharanee 'Barney' Rathna"]
  s.date = %q{2010-07-19}
  s.description = %q{A rational rudimentary database abstraction.}
  s.email = ["shane.hanna@gmail.com", "deepfryed@gmail.com"]
  s.extensions = ["ext/swift/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/swift/dbi.cc",
     "ext/swift/extconf.rb",
     "lib/swift.rb",
     "lib/swift/adapter.rb",
     "lib/swift/identity_map.rb",
     "lib/swift/pool.rb",
     "lib/swift/properties.rb",
     "lib/swift/property.rb",
     "lib/swift/resource.rb",
     "lib/swift/statement.rb",
     "swift.gemspec",
     "test/helper.rb",
     "test/test_resource.rb"
  ]
  s.homepage = %q{http://github.com/shanna/swift}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A rational rudimentary database abstraction.}
  s.test_files = [
    "test/helper.rb",
     "test/test_resource.rb",
     "examples/dbi.rb",
     "examples/async.rb",
     "examples/minimal.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

